version: '2'
services:

### Nginx Server Container ##################################

    nginx:
        build: ./nginx
        container_name: nginx
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "80:80"
        links:
            - php

### PHP Container ###########################################

    php:
        build: ./php
        container_name: php
        volumes:
            - ../:/var/www/laravel
            - ./logs/php/:/usr/local/var/log
        expose:
            - "9000"

### DATA Container ##########################################

    data:
        build: ./data
        container_name: data
        volumes:
            - /var/lib/mysql
            - /var/lib/postgresql/data
            - /var/lib/redis

### MySQL Container #########################################

    mysql:
        build: ./mysql
        container_name: mysql
        volumes_from:
            - data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        links:
            - php

### PostgreSQL Container ####################################

    postgres:
        build: ./postgres
        container_name: postgres
        volumes_from:
            - data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: homestead
            POSTGRES_USER: homestead
            POSTGRES_PASSWORD: secret
        links:
            - php

### Redis Container #########################################

    redis:
        build: ./redis
        container_name: redis
        volumes_from:
            - data
        ports:
            - "6379:6379"

### Add more Containers below ###############################
